### ISSUE TITLE
Is shebang correct?

### ISSUE THREAD

**Issue by ahangarha** [MCSH/cheat#4]
Hi

Is the shebang at the first line of [cheat.py](https://github.com/MCSH/cheat/blob/503ae3270c36323e620a59cb5f7e0ffb5b9c44b9/cheat.py#L1) correct? Is it necessary to link it to python in virtual env directory?

I think there is no need to do this since virtualenv itself manage to use the right path to python. Isn't it?

**Comment by MCSH** [comment]
I think it needs to be `/bin/env python` and there is a / missing.

Personally, I find it cleaner to use env in order to find the correct python version, although `python` could be used as well.

Pull Requests are welcome if /bin/env doesn't works on your system and you need to change it

**Comment by ahangarha** [comment]
I made a little research on web and found that using `/usr/bin/env python` works find withing or without virtualenv. Furthermore, I checked it on my system to make sure there is not problem. Just if one runs the code out of virtualenv, the version of python would be dependent on her default version.

**Comment by senaps** [comment]
I haven't used the shebang for a really long time, so can't offer any help on that part.
 I would fix the setup.py file though and we could use its entry_points, no shebang needed anymore.
and the application would run like before, just by invoking the `cheats` command.
